"""
SHL Individual Test Solutions catalog.
Data sourced from https://www.shl.com/solutions/products/product-catalog/
Restricted to Individual Test Solutions (Pre-packaged Job Solutions excluded).

Test Type codes:
  A = Ability & Aptitude
  B = Biodata & Situational Judgement
  C = Competencies
  D = Development & 360
  E = Assessment Exercises
  K = Knowledge & Skills
  P = Personality & Behavior
  S = Simulations
"""

CATALOG: list[dict] = [
    # ── Ability & Aptitude ────────────────────────────────────────────────
    {
        "name": "Verify Numerical Reasoning",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/verify-numerical-reasoning/",
        "test_type": ["A"],
        "description": "Measures the ability to understand and analyze numerical data, interpret graphs and tables, and draw logical conclusions. Suitable for professional and managerial roles.",
        "remote_testing": True,
        "adaptive": True,
        "duration_minutes": 17,
        "languages": ["English", "French", "German", "Spanish", "Chinese", "Dutch", "Portuguese"],
        "job_levels": ["Graduate", "Professional", "Manager"],
        "keywords": ["numerical", "quantitative", "data analysis", "math", "statistics", "finance", "analyst"],
    },
    {
        "name": "Verify Verbal Reasoning",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/verify-verbal-reasoning/",
        "test_type": ["A"],
        "description": "Measures the ability to understand written information and evaluate arguments. Suitable for roles requiring strong communication or analysis of written material.",
        "remote_testing": True,
        "adaptive": True,
        "duration_minutes": 17,
        "languages": ["English", "French", "German", "Spanish", "Dutch"],
        "job_levels": ["Graduate", "Professional", "Manager"],
        "keywords": ["verbal", "reading", "comprehension", "communication", "language", "writing", "editorial"],
    },
    {
        "name": "Verify Inductive Reasoning",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/verify-inductive-reasoning/",
        "test_type": ["A"],
        "description": "Measures the ability to identify patterns, logical rules, and trends in abstract information. Predicts learning potential and problem-solving ability.",
        "remote_testing": True,
        "adaptive": True,
        "duration_minutes": 24,
        "languages": ["English"],
        "job_levels": ["Graduate", "Professional", "Manager"],
        "keywords": ["inductive", "abstract", "reasoning", "pattern", "logic", "problem solving", "learning agility"],
    },
    {
        "name": "Verify Deductive Reasoning",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/verify-deductive-reasoning/",
        "test_type": ["A"],
        "description": "Assesses the ability to draw logical conclusions from a set of premises and identify flaws in arguments. Useful for analytical and consultancy roles.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English"],
        "job_levels": ["Graduate", "Professional", "Manager"],
        "keywords": ["deductive", "logic", "reasoning", "analysis", "consultant", "law", "policy"],
    },
    {
        "name": "Verify Calculation",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/verify-calculation/",
        "test_type": ["A"],
        "description": "Measures speed and accuracy in performing arithmetic calculations. Suitable for clerical, administrative, and data-entry roles.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 10,
        "languages": ["English", "German", "French"],
        "job_levels": ["Entry", "Clerical", "Administrative"],
        "keywords": ["calculation", "arithmetic", "clerical", "admin", "data entry", "accounts", "payroll"],
    },
    {
        "name": "Verify Checking",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/verify-checking/",
        "test_type": ["A"],
        "description": "Measures speed and accuracy in checking alphanumeric data. Relevant for roles requiring attention to detail in data-entry or administrative tasks.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 7,
        "languages": ["English"],
        "job_levels": ["Entry", "Clerical", "Administrative"],
        "keywords": ["checking", "accuracy", "attention to detail", "data entry", "clerical", "administrative"],
    },
    {
        "name": "Occupational Personality Questionnaire (OPQ32)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/opq32/",
        "test_type": ["P"],
        "description": "Industry-leading personality questionnaire measuring 32 dimensions of work-related personality. Used for selection, development, and succession planning across all levels.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": ["English", "French", "German", "Spanish", "Chinese", "Arabic", "Dutch", "Portuguese", "Russian", "Italian"],
        "job_levels": ["Entry", "Graduate", "Professional", "Manager", "Executive"],
        "keywords": ["personality", "behavior", "OPQ", "OPQ32", "leadership", "teamwork", "culture fit", "soft skills", "work style", "competency", "development"],
    },
    {
        "name": "OPQ32r",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/opq32r/",
        "test_type": ["P"],
        "description": "Revised version of OPQ32 using an ipsative (forced-choice) response format, reducing response bias. Measures 32 personality dimensions for selection and development.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": ["English", "French", "German", "Spanish", "Chinese"],
        "job_levels": ["Graduate", "Professional", "Manager", "Executive"],
        "keywords": ["personality", "ipsative", "forced choice", "OPQ32r", "behavior", "leadership", "development", "selection"],
    },
    {
        "name": "Motivation Questionnaire (MQ)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/motivation-questionnaire-mq/",
        "test_type": ["P"],
        "description": "Assesses 18 dimensions of motivation that influence how much energy an individual will put into their work. Used to predict engagement, retention, and job satisfaction.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": ["English", "French", "German", "Spanish"],
        "job_levels": ["Graduate", "Professional", "Manager"],
        "keywords": ["motivation", "engagement", "retention", "values", "drive", "energy", "job satisfaction", "culture"],
    },
    {
        "name": "General Ability (Verify G+)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/general-ability/",
        "test_type": ["A"],
        "description": "Adaptive measure of general cognitive ability (g) combining numerical, verbal, and inductive reasoning. Efficient broad measure for high-volume hiring.",
        "remote_testing": True,
        "adaptive": True,
        "duration_minutes": 36,
        "languages": ["English"],
        "job_levels": ["Graduate", "Professional", "Manager"],
        "keywords": ["general ability", "cognitive", "intelligence", "g factor", "aptitude", "reasoning", "broad ability"],
    },
    {
        "name": "Numerical Reasoning",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/numerical-reasoning/",
        "test_type": ["A"],
        "description": "Classic numerical reasoning test measuring ability to interpret data from charts, tables and graphs. Widely used for graduate and professional selection.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": ["English", "French", "German", "Spanish", "Dutch"],
        "job_levels": ["Graduate", "Professional"],
        "keywords": ["numerical", "data", "charts", "tables", "graphs", "finance", "banking", "analyst"],
    },
    {
        "name": "Verbal Reasoning",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/verbal-reasoning/",
        "test_type": ["A"],
        "description": "Classic verbal reasoning test assessing comprehension of passages and logical evaluation of statements. Used for graduate and professional selection.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 19,
        "languages": ["English", "French", "German", "Spanish"],
        "job_levels": ["Graduate", "Professional"],
        "keywords": ["verbal", "reading", "comprehension", "communication", "language"],
    },
    {
        "name": "Inductive Reasoning",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/inductive-reasoning/",
        "test_type": ["A"],
        "description": "Classic abstract/inductive reasoning test measuring ability to identify rules and patterns in abstract shapes. Predicts general problem-solving and learning.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": ["English"],
        "job_levels": ["Graduate", "Professional"],
        "keywords": ["inductive", "abstract", "patterns", "reasoning", "problem solving"],
    },
    {
        "name": "Mechanical Comprehension",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/mechanical-comprehension/",
        "test_type": ["A"],
        "description": "Measures understanding of mechanical and physical principles including forces, levers, and machinery. Essential for engineering, technical, and manufacturing roles.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": ["English"],
        "job_levels": ["Entry", "Technician", "Engineering"],
        "keywords": ["mechanical", "engineering", "technical", "physics", "manufacturing", "maintenance", "machinery", "operator"],
    },
    {
        "name": "Spatial Reasoning",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/spatial-reasoning/",
        "test_type": ["A"],
        "description": "Assesses ability to visualize and manipulate objects in 2D and 3D space. Relevant for design, architecture, engineering, and technical roles.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": ["English"],
        "job_levels": ["Entry", "Technician", "Professional"],
        "keywords": ["spatial", "visual", "3D", "design", "architecture", "engineering", "CAD", "technical"],
    },
    {
        "name": "Diagrammatic Reasoning",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/diagrammatic-reasoning/",
        "test_type": ["A"],
        "description": "Measures ability to follow and analyze complex diagrams and rules, relevant for IT, systems analysis, and process-oriented roles.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": ["English"],
        "job_levels": ["Graduate", "Professional"],
        "keywords": ["diagrammatic", "systems", "IT", "process", "logic", "flowchart", "analyst", "software"],
    },
    # ── Knowledge & Skills ────────────────────────────────────────────────
    {
        "name": "Java 8 (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/java-8-new/",
        "test_type": ["K"],
        "description": "Assesses knowledge and application of Java 8 programming concepts including lambdas, streams, concurrency, and OOP principles.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 45,
        "languages": ["English"],
        "job_levels": ["Entry", "Junior", "Mid-level", "Senior"],
        "keywords": ["java", "java 8", "programming", "developer", "software engineer", "backend", "OOP", "lambdas", "streams", "coding"],
    },
    {
        "name": "Java Spring Framework",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/java-spring-framework/",
        "test_type": ["K"],
        "description": "Tests knowledge of the Spring Framework including Spring Boot, dependency injection, MVC, data access, and security.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 45,
        "languages": ["English"],
        "job_levels": ["Mid-level", "Senior"],
        "keywords": ["java", "spring", "spring boot", "backend", "microservices", "REST API", "developer", "framework"],
    },
    {
        "name": "Python (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/python-new/",
        "test_type": ["K"],
        "description": "Evaluates Python programming proficiency including data structures, OOP, file I/O, libraries (pandas, numpy), and scripting.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 45,
        "languages": ["English"],
        "job_levels": ["Entry", "Junior", "Mid-level", "Senior"],
        "keywords": ["python", "programming", "developer", "data science", "scripting", "automation", "pandas", "numpy", "machine learning"],
    },
    {
        "name": "SQL (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/sql-new/",
        "test_type": ["K"],
        "description": "Assesses SQL knowledge including queries, joins, aggregations, stored procedures, and database design.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 30,
        "languages": ["English"],
        "job_levels": ["Entry", "Junior", "Mid-level"],
        "keywords": ["SQL", "database", "queries", "joins", "data analyst", "DBA", "MySQL", "PostgreSQL", "data engineer"],
    },
    {
        "name": "JavaScript (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/javascript-new/",
        "test_type": ["K"],
        "description": "Tests JavaScript programming skills including ES6+, DOM manipulation, async/await, closures, and modern frameworks knowledge.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 45,
        "languages": ["English"],
        "job_levels": ["Entry", "Junior", "Mid-level", "Senior"],
        "keywords": ["javascript", "JS", "frontend", "web developer", "ES6", "Node.js", "React", "Angular", "Vue"],
    },
    {
        "name": "C++ (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/c-plus-plus-new/",
        "test_type": ["K"],
        "description": "Evaluates C++ programming skills including memory management, STL, templates, object-oriented design, and performance optimization.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 45,
        "languages": ["English"],
        "job_levels": ["Mid-level", "Senior"],
        "keywords": ["C++", "systems programming", "embedded", "game development", "performance", "low-level", "memory management"],
    },
    {
        "name": ".NET Framework 4.5",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/net-framework-4-5/",
        "test_type": ["K"],
        "description": "Tests knowledge of the .NET 4.5 Framework including C#, ASP.NET, LINQ, WCF, and Entity Framework.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 45,
        "languages": ["English"],
        "job_levels": ["Mid-level", "Senior"],
        "keywords": [".NET", "C#", "ASP.NET", "Microsoft", "developer", "backend", "enterprise"],
    },
    {
        "name": "Microsoft Excel 2016",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/microsoft-excel-2016/",
        "test_type": ["K"],
        "description": "Assesses proficiency in Microsoft Excel including formulas, pivot tables, charts, macros, and data analysis features.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 30,
        "languages": ["English"],
        "job_levels": ["Entry", "Clerical", "Professional"],
        "keywords": ["Excel", "spreadsheet", "Microsoft Office", "data", "analyst", "finance", "admin", "accountant"],
    },
    {
        "name": "Microsoft Word 2016",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/microsoft-word-2016/",
        "test_type": ["K"],
        "description": "Tests proficiency in Microsoft Word including document formatting, styles, mail merge, and collaboration features.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 30,
        "languages": ["English"],
        "job_levels": ["Entry", "Clerical", "Administrative"],
        "keywords": ["Word", "Microsoft Office", "documentation", "admin", "secretary", "clerical"],
    },
    {
        "name": "Accounting and Finance",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/accounting-and-finance/",
        "test_type": ["K"],
        "description": "Evaluates knowledge of accounting principles, financial reporting, budgeting, and compliance. Suitable for finance and accounting roles.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 40,
        "languages": ["English"],
        "job_levels": ["Entry", "Graduate", "Professional"],
        "keywords": ["accounting", "finance", "GAAP", "financial reporting", "budgeting", "CPA", "bookkeeping", "auditing"],
    },
    {
        "name": "Customer Service",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/customer-service/",
        "test_type": ["K"],
        "description": "Assesses knowledge and application of customer service best practices, complaint handling, and communication. Used for frontline and support roles.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": ["English"],
        "job_levels": ["Entry", "Frontline"],
        "keywords": ["customer service", "support", "helpdesk", "complaint handling", "CX", "call center", "retail"],
    },
    {
        "name": "Sales Representative",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/sales-representative/",
        "test_type": ["K"],
        "description": "Tests knowledge of effective sales techniques, customer relationship management, and sales processes.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": ["English"],
        "job_levels": ["Entry", "Junior", "Professional"],
        "keywords": ["sales", "selling", "CRM", "B2B", "B2C", "account management", "business development"],
    },
    {
        "name": "IT Business Analyst",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/it-business-analyst/",
        "test_type": ["K"],
        "description": "Evaluates knowledge of business analysis techniques, requirements gathering, process modeling, and stakeholder communication for IT BA roles.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 40,
        "languages": ["English"],
        "job_levels": ["Mid-level", "Professional"],
        "keywords": ["business analyst", "BA", "requirements", "process modeling", "stakeholders", "IT", "agile", "scrum"],
    },
    {
        "name": "Automata - Fix the Code",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/automata-fix-the-code/",
        "test_type": ["K"],
        "description": "Practical coding challenge where candidates debug and fix broken code. Assesses real-world programming ability across multiple languages.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 30,
        "languages": ["English"],
        "job_levels": ["Entry", "Junior", "Mid-level"],
        "keywords": ["coding", "debugging", "programming", "software engineer", "developer", "practical", "hands-on"],
    },
    {
        "name": "Automata Pro",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/automata-pro/",
        "test_type": ["K"],
        "description": "Advanced coding simulation platform for assessing software developers across real-world tasks. Tests full-stack, backend, or frontend skills in a live coding environment.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 60,
        "languages": ["English"],
        "job_levels": ["Mid-level", "Senior"],
        "keywords": ["coding", "software engineer", "developer", "full stack", "backend", "frontend", "practical", "simulation"],
    },
    # ── Situational Judgement ─────────────────────────────────────────────
    {
        "name": "Customer Contact Scenarios",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/customer-contact-scenarios/",
        "test_type": ["B"],
        "description": "Situational judgement test presenting realistic customer interaction scenarios. Measures judgment and decision-making for customer-facing roles.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": ["English"],
        "job_levels": ["Entry", "Frontline"],
        "keywords": ["customer service", "SJT", "situational judgement", "frontline", "retail", "banking", "call center"],
    },
    {
        "name": "Supervisory Scenarios",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/supervisory-scenarios/",
        "test_type": ["B"],
        "description": "Situational judgement test for first-line supervisors covering team management, conflict resolution, and performance issues.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 30,
        "languages": ["English"],
        "job_levels": ["Supervisor", "Team Lead", "Manager"],
        "keywords": ["supervisor", "team lead", "management", "SJT", "situational judgement", "conflict", "performance"],
    },
    {
        "name": "Graduate 8 (GRT2)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/graduate-8-grt2/",
        "test_type": ["A"],
        "description": "Comprehensive ability battery for graduate-level candidates covering verbal, numerical, and abstract reasoning. Used for graduate recruitment.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 60,
        "languages": ["English"],
        "job_levels": ["Graduate"],
        "keywords": ["graduate", "entry level", "verbal", "numerical", "abstract", "graduate scheme", "campus hiring", "early career"],
    },
    {
        "name": "Managerial and Graduate Item Bank (MGIB)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/managerial-and-graduate-item-bank/",
        "test_type": ["A"],
        "description": "Comprehensive ability test battery for managerial and graduate candidates, covering verbal, numerical, and abstract reasoning at a higher level.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 60,
        "languages": ["English"],
        "job_levels": ["Graduate", "Manager", "Professional"],
        "keywords": ["manager", "graduate", "verbal", "numerical", "abstract", "management", "leadership", "senior"],
    },
    {
        "name": "Workplace English (WE)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/workplace-english/",
        "test_type": ["K"],
        "description": "Assesses English language proficiency in workplace contexts including reading comprehension, business writing, and grammar. Used for multilingual workforces.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 30,
        "languages": ["English"],
        "job_levels": ["Entry", "Professional"],
        "keywords": ["English", "language", "communication", "writing", "ESL", "multilingual", "global", "international"],
    },
    {
        "name": "Workplace Safety",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/workplace-safety/",
        "test_type": ["K"],
        "description": "Evaluates knowledge of workplace health and safety regulations, hazard identification, and safe work practices. Suitable for industrial and operational roles.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": ["English"],
        "job_levels": ["Entry", "Frontline", "Technician"],
        "keywords": ["safety", "health and safety", "HSE", "industrial", "manufacturing", "warehouse", "operations", "compliance"],
    },
    {
        "name": "General Staffing Ability (GSA)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/general-staffing-ability/",
        "test_type": ["A"],
        "description": "Short ability measure covering basic verbal, numerical, and checking skills. Designed for high-volume frontline and clerical hiring.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 15,
        "languages": ["English"],
        "job_levels": ["Entry", "Frontline", "Clerical"],
        "keywords": ["general ability", "frontline", "volume hiring", "clerical", "entry level", "basic skills", "warehouse", "retail", "call center", "GSA"],
    },
    {
        "name": "Technology Professional 8.0 (TP8)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/technology-professional-8/",
        "test_type": ["A"],
        "description": "Ability test designed for technology professionals measuring verbal, numerical, and inductive reasoning relevant to IT and technical roles.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 45,
        "languages": ["English"],
        "job_levels": ["Professional", "Mid-level", "Senior"],
        "keywords": ["technology", "IT", "technical", "software", "developer", "systems", "engineer", "tech professional"],
    },
    {
        "name": "Operational Ability",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/operational-ability/",
        "test_type": ["A"],
        "description": "Measures practical reasoning ability relevant to operational, technical, and skilled trade roles. Covers mechanical, spatial, and numerical content.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 30,
        "languages": ["English"],
        "job_levels": ["Entry", "Technician", "Operator"],
        "keywords": ["operational", "trades", "technician", "practical", "mechanical", "spatial", "operator", "manufacturing"],
    },
    {
        "name": "Personality for Frontline",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/personality-for-frontline/",
        "test_type": ["P"],
        "description": "Shortened personality questionnaire optimized for frontline and high-volume hiring scenarios. Assesses key behavioral dimensions for customer-facing and operational roles.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 15,
        "languages": ["English"],
        "job_levels": ["Entry", "Frontline"],
        "keywords": ["personality", "frontline", "volume hiring", "customer service", "retail", "warehouse", "behavior"],
    },
    {
        "name": "Sales Assessment",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/sales-assessment/",
        "test_type": ["P", "K"],
        "description": "Comprehensive sales assessment combining personality and knowledge components. Predicts sales performance, customer focus, and resilience.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 30,
        "languages": ["English"],
        "job_levels": ["Entry", "Junior", "Professional"],
        "keywords": ["sales", "business development", "account manager", "B2B", "B2C", "revenue", "cold calling", "closing", "resilience"],
    },
    {
        "name": "Universal Competency Framework (UCF) 360",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/ucf-360/",
        "test_type": ["D", "C"],
        "description": "360-degree feedback tool based on SHL's Universal Competency Framework. Collects multi-rater feedback across leadership and behavioral competencies for development.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 30,
        "languages": ["English", "French", "German", "Spanish"],
        "job_levels": ["Manager", "Senior Manager", "Executive"],
        "keywords": ["360 feedback", "leadership development", "competency", "multi-rater", "executive", "development", "coaching"],
    },
    {
        "name": "Scenarios – Call Center",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/scenarios-call-center/",
        "test_type": ["B"],
        "description": "Situational judgement test specifically designed for call center and customer support roles. Assesses handling of difficult calls, escalations, and service quality.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English"],
        "job_levels": ["Entry", "Frontline"],
        "keywords": ["call center", "customer support", "helpdesk", "telephone", "SJT", "inbound", "outbound", "CX"],
    },
    {
        "name": "Scenarios – Retail",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/scenarios-retail/",
        "test_type": ["B"],
        "description": "Situational judgement test designed for retail environments. Evaluates responses to common retail scenarios including customer service, loss prevention, and teamwork.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English"],
        "job_levels": ["Entry", "Frontline"],
        "keywords": ["retail", "store", "shop", "customer", "SJT", "sales associate", "cashier", "frontline"],
    },
    {
        "name": "Scenarios – Banking",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/scenarios-banking/",
        "test_type": ["B"],
        "description": "Situational judgement test for banking and financial services roles. Covers compliance, customer interaction, and ethical decision-making in a banking context.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": ["English"],
        "job_levels": ["Entry", "Graduate", "Professional"],
        "keywords": ["banking", "finance", "compliance", "customer", "SJT", "financial services", "teller", "relationship manager"],
    },
    {
        "name": "Data Entry (Alphanumeric)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/data-entry-alphanumeric/",
        "test_type": ["K"],
        "description": "Practical speed and accuracy test for alphanumeric data entry. Used for data-entry operators and administrative roles.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 10,
        "languages": ["English"],
        "job_levels": ["Entry", "Clerical"],
        "keywords": ["data entry", "typing", "alphanumeric", "accuracy", "speed", "clerical", "admin", "operator"],
    },
    {
        "name": "Typing Speed and Accuracy",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/typing-speed-and-accuracy/",
        "test_type": ["K"],
        "description": "Measures typing speed (WPM) and accuracy. Used for administrative, secretarial, and data-entry roles.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 10,
        "languages": ["English"],
        "job_levels": ["Entry", "Clerical", "Administrative"],
        "keywords": ["typing", "WPM", "speed", "accuracy", "secretary", "admin", "data entry"],
    },
    {
        "name": "Agile Software Development",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/agile-software-development/",
        "test_type": ["K"],
        "description": "Tests understanding of Agile principles, Scrum, Kanban, sprint planning, retrospectives, and agile team dynamics.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 30,
        "languages": ["English"],
        "job_levels": ["Mid-level", "Senior", "Manager"],
        "keywords": ["agile", "scrum", "kanban", "software", "developer", "project manager", "product owner", "sprint", "DevOps"],
    },
    {
        "name": "DevOps",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/devops/",
        "test_type": ["K"],
        "description": "Assesses knowledge of DevOps practices including CI/CD, containerization (Docker/Kubernetes), infrastructure as code, and monitoring.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 40,
        "languages": ["English"],
        "job_levels": ["Mid-level", "Senior"],
        "keywords": ["DevOps", "CI/CD", "Docker", "Kubernetes", "infrastructure", "cloud", "AWS", "Azure", "pipeline", "SRE"],
    },
    {
        "name": "Cyber Security",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/cyber-security/",
        "test_type": ["K"],
        "description": "Evaluates knowledge of cybersecurity principles including threat modeling, network security, cryptography, and incident response.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 40,
        "languages": ["English"],
        "job_levels": ["Mid-level", "Senior"],
        "keywords": ["cybersecurity", "security", "infosec", "penetration testing", "network security", "SOC", "CISO", "encryption"],
    },
    {
        "name": "Project Management Professional",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/project-management-professional/",
        "test_type": ["K"],
        "description": "Tests knowledge of project management methodologies (PMP, Prince2), planning, risk management, resource allocation, and stakeholder management.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 40,
        "languages": ["English"],
        "job_levels": ["Professional", "Manager"],
        "keywords": ["project management", "PMP", "Prince2", "planning", "risk", "stakeholders", "PMO", "program manager"],
    },
    {
        "name": "Administrative Professional",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/administrative-professional/",
        "test_type": ["K"],
        "description": "Comprehensive assessment for administrative roles covering office procedures, business communication, scheduling, and organizational skills.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 35,
        "languages": ["English"],
        "job_levels": ["Entry", "Clerical", "Administrative"],
        "keywords": ["admin", "administrative assistant", "executive assistant", "office manager", "scheduling", "PA", "secretary"],
    },
    {
        "name": "Call Center",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/call-center/",
        "test_type": ["K"],
        "description": "Assesses skills and knowledge for call center roles including communication, customer handling, multi-tasking, and problem-solving under pressure.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 30,
        "languages": ["English"],
        "job_levels": ["Entry", "Frontline"],
        "keywords": ["call center", "customer service", "telephone", "inbound", "outbound", "BPO", "support", "communication"],
    },
    {
        "name": "Leadership Report (OPQ)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/leadership-report-opq/",
        "test_type": ["P", "C"],
        "description": "OPQ-based report interpreting personality profile against leadership competencies. Identifies leadership strengths, risks, and development areas.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": ["English", "French", "German"],
        "job_levels": ["Manager", "Senior Manager", "Executive"],
        "keywords": ["leadership", "OPQ", "executive", "manager", "development", "succession", "competency", "C-suite"],
    },
    {
        "name": "Team Impact Report (OPQ)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/team-impact-report-opq/",
        "test_type": ["P"],
        "description": "OPQ-based report describing an individual's preferred team roles and how they contribute to and work within teams.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": ["English"],
        "job_levels": ["Graduate", "Professional", "Manager"],
        "keywords": ["teamwork", "collaboration", "OPQ", "team roles", "personality", "Belbin", "team dynamics", "interpersonal"],
    },
    {
        "name": "Remote Worker Assessment",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/remote-worker-assessment/",
        "test_type": ["P", "B"],
        "description": "Assesses personality traits and situational judgement relevant to remote/hybrid working: self-discipline, communication, digital collaboration, and resilience.",
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English"],
        "job_levels": ["Entry", "Professional", "Manager"],
        "keywords": ["remote work", "hybrid", "work from home", "WFH", "self-management", "digital", "collaboration", "resilience"],
    },
]


def get_catalog() -> list[dict]:
    return CATALOG


def get_assessment_by_name(name: str) -> dict | None:
    name_lower = name.lower()
    for item in CATALOG:
        if item["name"].lower() == name_lower:
            return item
    return None


def search_catalog_by_keywords(keywords: list[str], top_k: int = 10) -> list[dict]:
    """Simple keyword-based fallback search."""
    scored = []
    for item in CATALOG:
        score = 0
        text = " ".join([
            item["name"],
            item["description"],
            " ".join(item["keywords"]),
            " ".join(item["test_type"]),
            " ".join(item.get("job_levels", [])),
        ]).lower()
        for kw in keywords:
            if kw.lower() in text:
                score += 1
        if score > 0:
            scored.append((score, item))
    scored.sort(key=lambda x: x[0], reverse=True)
    return [item for _, item in scored[:top_k]]
